export const string = {
  ErrorLabel: "Data download error",
  TryAgain: "Try Again",
  Loading: " Loading...",
  MainTitle: "List of Stackoverflow tags",
  NextPage: " Next Page",
  PreviousPage: "Previous Page",
  Desc: "Desc",
  Asc: "Asc",
  Popular: "Popular",
  Activity: "Activity",
  Name: "Name",
  Save: "Save changes",
  Sort: "Sort",
  Order: "Order",
  Questions: "questions",
  TagLabel: "Tag name",
  Page: "Page",
  NumberOfElements: "Number of elements",
  Empty: "Tag list is empty",
};
